language: go

go: stable

before_install:
  - echo Installing dependencies
  - sudo apt-get -qq install xfslibs-dev uuid-dev libtool-bin
    e2fsprogs automake gcc libuuid1 quota attr libattr1-dev make
    libacl1-dev libaio-dev xfsprogs libgdbm-dev gawk fio dbench
    uuid-runtime python sqlite3 fuse
  - sudo useradd fsgqa
  - sudo groupadd fsgqa || true
  - sudo useradd 123456-fsgqa
  - echo
  - echo Enabling FUSE
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

install:
  - make -j $(nproc)

jobs:
  include:
    - name: loopback
      script:
        - go get -d github.com/hanwen/go-fuse/...
        - git -C $(go env GOPATH)/src/github.com/hanwen/go-fuse log --oneline -1
        - go install github.com/hanwen/go-fuse/example/loopback
        - sudo PATH=$HOME/go/bin:$PATH ./check-loopback
    - name: gocryptfs
      script:
        - go get -d github.com/rfjakob/gocryptfs/...
        - git -C $(go env GOPATH)/src/github.com/hanwen/go-fuse log --oneline -1
        - git -C $(go env GOPATH)/src/github.com/rfjakob/gocryptfs log --oneline -1
        - go install github.com/rfjakob/gocryptfs
        - sudo PATH=$HOME/go/bin:$PATH ./check-gocryptfs
